### ISSUE TITLE
Theme installation failed.

### ISSUE THREAD

**Issue by yanncarlier** [knomepasi/ubuntu-community-wordpress-theme#10]
Installing Theme from uploaded file: ubuntu-community-wordpress-theme-master.zip
Unpacking the package…

Installing the theme…

The package could not be installed. The theme is missing the style.css stylesheet.

Theme installation failed.

**Comment by knomepasi** [comment]
The theme download isn't working like that as the theme files need to be in a subdirectory of the repository for technical reasons.

I've pushed a new revision with a downloadable .zip file for automatical installations.
