### ISSUE TITLE
Support low resolution devices

### ISSUE THREAD

**Issue by eveninglily** [knomepasi/ubuntu-community-wordpress-theme#3]
Currently, on older devices with a lower resolution, the page does not fit fully width-wise (users will have to scroll left/right)

![sf0vv5p](https://cloud.githubusercontent.com/assets/2966094/12527671/be1b5c2e-c14d-11e5-8244-34fc26f1fc7e.png)

The device tested with was a Galaxy S3, which has a horizontal width of 360 pixels

**Comment by knomepasi** [comment]
Preliminary support for devices under 640 pixels (but not lower than 320px) has been landed with c3269669dbb362186dc424d2d8e8b260b6aca171. Javascript-ran menu TBD.

**Comment by eveninglily** [comment]
Works great :) :+1:
