### ISSUE TITLE
Custom link categories not shown

### ISSUE THREAD

**Issue by pleia2** [knomepasi/ubuntu-community-wordpress-theme#7]
We're using a right hand menu for navigation on ubuntu-us.org, but this does not exist in this theme and our custom link categories configured through the regular WordPress interface (not using Thematic) aren't showing up at all. Screenshot of theme attempting to be applied, see the live site for what is expected.

![ubuntu-us-test-knome-theme-1](https://cloud.githubusercontent.com/assets/879924/12876806/87d09276-cdbc-11e5-966d-f97de17c8c24.png)

**Comment by knomepasi** [comment]
This will simply require another widget area set up for the sidebar.
