### ISSUE TITLE
Footer link color not respected on live site

### ISSUE THREAD

**Issue by tjyrinki** [knomepasi/ubuntu-community-wordpress-theme#9]
Hi. When looking at http://ubuntu-fi.org/ bottom bar sections, the links are there but they are not colored. However, in the customizing theme page in WP, the links including blog links are correctly colored orange. Something seems preventing this when the site is viewed?

**Comment by knomepasi** [comment]
Actually the behavior on the user interface is intended; the links should remain gray until hovered. I believe you want the links to be always colored even without hovering – I will add an option for this in the next release.

**Comment by knomepasi** [comment]
Fixed in 67043ec02e0b6f348df40d7094d4bae2f59ee326.
